version: '3.8'
services:
  managementservice:
    build:
      context: ./ManagementService
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    container_name: ManagementService
    volumes:
      - /home/ubuntu/hlot_/hlot_be_service/temp:/var/temp
      - /home/ubuntu/hlot_/hlot_be_service/logs/cs:/logs

