version: '3'
services:
    node_nginx:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '/home/ubuntu/hlot_/hlot_fe/log:/var/log'
        ports:
            - "80:80"
        stdin_open: true # 추가
        tty: true        # 추가
